### PR TITLE
feat: #331 えんえんとかほざいたら泣き部屋に投げ込む

### LINKED ISSUE #331: えんえんとかほざいたら泣き部屋に投げ込む

### PR DESCRIPTION
**Pull request by book000**
- close #331

### CODE REVIEW

**Comment by book000** [comment]
@jaotan review

**Review by jaotan — DISMISSED** [review]
It was reviewed by a request by comment.

**Comment by book000** [comment]
@jaotan review

**Review by jaotan — APPROVED** [review]
It was reviewed by a request by comment.

**Pull request merged**
